version: "3"
services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  webapp:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
