services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  webapp:
    build: .
    ports:
      - "80:8888"
    volumes:
      #########################
      # temporary cahnge for dev
      # - ./files:/opt/rtb/files:rw -> - ./:/opt/rtb:rw
      - ./:/opt/rtb:rw
    #environment:
      #- COMPOSE_CONVERT_WINDOWS_PATHS=1
